FROM devkitpro/devkitarm:latest AS build
WORKDIR /work
# copy your GAS file(s)
COPY mixer_asm.S .

# If you need CPP macros in the .S file:
# RUN arm-none-eabi-gcc -x assembler-with-cpp -mcpu=arm7tdmi -mthumb -c mixer_asm.S -o mixer_asm.o
RUN arm-none-eabi-as -mcpu=arm7tdmi -mthumb -o mixer_asm.o mixer_asm.S

# keep artifact at /work/mixer_asm.o
