const mm = @import("../maxmod.zig");

pub const note_table_oct: [30]mm.Byte = [30]mm.Byte{ 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9 };
pub const note_table_mod: [109]mm.Byte = [109]mm.Byte{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0 };
pub const ST3_FREQTABLE: [12]mm.Hword = [12]mm.Hword{
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1712) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1616) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1524) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1440) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1356) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1280) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1208) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1140) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1076) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1016) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 960) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 907) * @as(c_int, 8))))),
};
pub const IT_PitchTable: [240]mm.Hword align(4) = [240]mm.Hword{
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2048))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2170))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2299))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2435))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2580))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2734))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2896))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3069))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3251))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3444))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3649))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3866))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4096))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4340))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4598))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4871))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5161))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5468))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5793))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6137))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6502))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6889))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 7298))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 7732))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8192))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8679))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 9195))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 9742))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 10321))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 10935))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 11585))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 12274))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 13004))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 13777))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 14596))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 15464))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 16384))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 17358))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 18390))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 19484))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 20643))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 21870))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 23170))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 24548))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26008))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27554))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29193))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 30929))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32768))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34716))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36781))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38968))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41285))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43740))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 46341))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49097))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 52016))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 55109))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 58386))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 61858))))),
    0,
    0,
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3897))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8026))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 12400))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 17034))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 21944))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27146))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32657))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38496))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44682))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 51236))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 58179))))),
    1,
    0,
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 7794))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 16051))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 24800))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34068))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43888))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 54292))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65314))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 11456))))),
    3,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 23828))))),
    3,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36936))))),
    3,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 50823))))),
    3,
    0,
    4,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 15588))))),
    4,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32103))))),
    4,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49600))))),
    4,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2601))))),
    5,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 22240))))),
    5,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43048))))),
    5,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65092))))),
    5,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 22912))))),
    6,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 47656))))),
    6,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8336))))),
    7,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36110))))),
    7,
    0,
    8,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 31176))))),
    8,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64205))))),
    8,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33663))))),
    9,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5201))))),
    10,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44481))))),
    10,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 20559))))),
    11,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64648))))),
    11,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 45823))))),
    12,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29776))))),
    13,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 16671))))),
    14,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6684))))),
    15,
    0,
    16,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 62352))))),
    16,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 62875))))),
    17,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1790))))),
    19,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 10403))))),
    20,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 23425))))),
    21,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41118))))),
    22,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 63761))))),
    23,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26111))))),
    25,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 59552))))),
    26,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33342))))),
    28,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 13368))))),
    30,
};
