const mm = @import("../maxmod.zig");

pub const note_table_oct: [30]mm.Byte = [30]mm.Byte{ 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9 };
pub const note_table_mod: [109]mm.Byte = [109]mm.Byte{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0 };
pub const ST3_FREQTABLE: [12]mm.Hword = [12]mm.Hword{
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1712) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1616) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1524) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1440) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1356) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1280) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1208) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1140) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1076) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1016) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 960) * @as(c_int, 8))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 907) * @as(c_int, 8))))),
};
pub const IT_PitchTable: [240]mm.Hword align(4) = [240]mm.Hword{
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2048))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2170))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2299))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2435))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2580))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2734))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2896))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3069))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3251))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3444))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3649))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3866))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4096))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4340))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4598))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4871))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5161))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5468))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5793))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6137))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6502))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6889))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 7298))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 7732))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8192))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8679))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 9195))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 9742))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 10321))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 10935))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 11585))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 12274))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 13004))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 13777))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 14596))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 15464))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 16384))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 17358))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 18390))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 19484))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 20643))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 21870))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 23170))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 24548))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26008))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27554))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29193))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 30929))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32768))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34716))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36781))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38968))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41285))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43740))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 46341))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49097))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 52016))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 55109))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 58386))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 61858))))),
    0,
    0,
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3897))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8026))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 12400))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 17034))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 21944))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27146))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32657))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38496))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44682))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 51236))))),
    1,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 58179))))),
    1,
    0,
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 7794))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 16051))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 24800))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34068))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43888))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 54292))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65314))))),
    2,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 11456))))),
    3,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 23828))))),
    3,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36936))))),
    3,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 50823))))),
    3,
    0,
    4,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 15588))))),
    4,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32103))))),
    4,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49600))))),
    4,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2601))))),
    5,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 22240))))),
    5,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43048))))),
    5,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65092))))),
    5,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 22912))))),
    6,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 47656))))),
    6,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8336))))),
    7,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36110))))),
    7,
    0,
    8,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 31176))))),
    8,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64205))))),
    8,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33663))))),
    9,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5201))))),
    10,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44481))))),
    10,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 20559))))),
    11,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64648))))),
    11,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 45823))))),
    12,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29776))))),
    13,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 16671))))),
    14,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6684))))),
    15,
    0,
    16,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 62352))))),
    16,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 62875))))),
    17,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1790))))),
    19,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 10403))))),
    20,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 23425))))),
    21,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41118))))),
    22,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 63761))))),
    23,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26111))))),
    25,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 59552))))),
    26,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33342))))),
    28,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 13368))))),
    30,
};

pub const mpp_TABLE_LinearSlideUpTable = [_]mm.Hword{
    0,
    237,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 475))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 714))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 953))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1194))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1435))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1677))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1920))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2164))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2409))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2655))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2902))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3149))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3397))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3647))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3897))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4148))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4400))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4653))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4907))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5157))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5417))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5674))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5932))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6190))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6449))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6710))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6971))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 7233))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 7496))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 7761))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8026))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8292))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8559))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8027))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 9096))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 9366))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 9636))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 9908))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 10181))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 10455))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 10730))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 11006))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 11283))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 11560))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 11839))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 12119))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 12400))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 12682))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 12965))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 13249))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 13533))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 13819))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 14106))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 14394))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 14684))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 14974))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 15265))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 15557))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 15850))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 16145))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 16440))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 16737))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 17034))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 17333))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 17633))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 17933))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 18235))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 18538))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 21315))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 21629))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 21944))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 22260))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 22578))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 22897))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 23216))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 23537))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 23860))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 24183))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 24507))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 24833))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 25160))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 25488))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 25817))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26148))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26479))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26812))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27146))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27481))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27818))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28155))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28494))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28834))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29175))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29518))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29862))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 30207))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 30553))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 30900))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 31248))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 31599))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 31951))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32303))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32657))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33012))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33369))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33726))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34085))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34446))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34807))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 35170))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 35534))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 35900))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36267))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36635))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 37004))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 37375))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 37747))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38121))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38496))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38872))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 39250))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 39629))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 40009))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 40391))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 40774))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41158))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41544))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41932))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 42320))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 42710))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43102))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43495))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43889))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44285))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44682))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 45081))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 45481))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 45882))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 46285))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 46690))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 47095))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 47503))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 47917))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 48322))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 48734))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49147))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49562))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49978))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 50396))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 50815))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 51236))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 51658))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 52082))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 52507))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 52934))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 53363))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 53793))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 54224))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 54658))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 55092))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 55529))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 55966))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 56406))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 56847))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 57289))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 57734))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 58179))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 58627))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 59076))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 59527))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 59979))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 60433))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 60889))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 61346))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 61805))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 62265))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 62727))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 63191))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 63657))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64124))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64593))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65064))))),
    0,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 474))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 950))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1427))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 1906))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2387))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 2870))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3355))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 3841))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4327))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 4818))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5310))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 5803))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6298))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 6795))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 7294))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 7794))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8296))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 8800))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 9306))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 9814))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 10323))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 10835))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 11348))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 11863))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 12380))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 12899))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 13419))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 13942))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 14467))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 14993))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 15521))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 16051))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 16583))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 17117))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 17653))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 18191))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 18731))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 19273))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 19817))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 20362))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 20910))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 21460))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 22011))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 22565))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 23121))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 23678))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 24238))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 24800))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 25363))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 25929))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 25497))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27067))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27639))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28213))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28789))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29367))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29947))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 30530))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 31114))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 31701))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32289))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32880))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33473))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34068))))),
};
pub const mpp_TABLE_LinearSlideDownTable = [_]mm.Hword{
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65535))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65300))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65065))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64830))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64596))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64364))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64132))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 63901))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 63670))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 63441))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 63212))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 62984))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 62757))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 62531))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 62306))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 62081))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 61858))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 61635))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 61413))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 61191))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 60971))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 60751))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 60532))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 60314))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 60097))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 59880))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 59664))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 59449))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 59235))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 59022))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 58809))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 58597))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 58386))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 58176))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 57966))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 57757))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 57549))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 57341))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 57135))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 56929))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 56724))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 56519))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 56316))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 56113))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 55911))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 55709))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 55508))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 55308))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 55109))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 54910))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 54713))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 54515))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 54319))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 54123))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 53928))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 53734))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 53540))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 53347))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 53155))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 52963))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 52773))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 52582))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 52393))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 52204))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 52016))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 51829))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 51642))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 51456))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 51270))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 51085))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 50901))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 50718))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 50535))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 50353))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 50172))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49991))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49811))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49631))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49452))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49274))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 49097))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 48920))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 48743))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 48568))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 48393))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 48128))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 48044))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 47871))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 47699))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 47527))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 47356))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 47185))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 47015))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 46846))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 46008))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 45842))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 45677))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 45512))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 45348))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 45185))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 45022))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44859))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44698))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44537))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44376))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44216))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 44057))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43898))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43740))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43582))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43425))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43269))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 43113))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 42958))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 42803))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 42649))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 42495))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 42342))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 42189))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 42037))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41886))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41735))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41584))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41434))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41285))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 41136))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 40988))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 40840))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 40639))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 40566))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 40400))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 40253))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 40110))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 39965))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 39821))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 39678))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 39535))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 39392))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 39250))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 39109))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38968))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38828))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38688))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38548))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38409))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38271))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 38133))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 37996))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 37859))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 37722))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 37586))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 37451))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 37316))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 37181))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 37047))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36914))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36781))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36648))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36516))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36385))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36254))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 36123))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 35993))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 35863))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 35734))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 35605))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 35477))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 35349))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 35221))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 35095))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34968))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34842))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34716))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34591))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34467))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34343))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34219))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 34095))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33973))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33850))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33728))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33607))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33486))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33365))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33245))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33125))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 33005))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32887))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32768))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32650))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32532))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32415))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32298))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32182))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 32066))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 30157))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 30048))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29940))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29832))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29725))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29618))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29511))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29405))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29299))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29193))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 29088))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28983))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28879))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28774))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28671))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28567))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28464))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28362))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28260))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28158))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 28056))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27955))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27855))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27754))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27654))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27554))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27455))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27356))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27258))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27159))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 27062))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26964))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26867))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26770))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26674))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26577))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26482))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26386))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26291))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26196))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26102))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 26008))))),
};
pub const mpp_TABLE_FineLinearSlideUpTable: [16]mm.Hword = [16]mm.Hword{
    0,
    59,
    118,
    178,
    237,
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 296))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 356))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 415))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 475))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 535))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 594))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 654))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 714))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 773))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 833))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 893))))),
};
pub const mpp_TABLE_FineLinearSlideDownTable: [16]mm.Hword = [16]mm.Hword{
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65535))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65477))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65418))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65359))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65300))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65241))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65182))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65359))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65065))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 65006))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64947))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64888))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64830))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64772))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64713))))),
    @as(mm.Hword, @bitCast(@as(c_short, @truncate(@as(c_int, 64645))))),
};

pub const mpp_effect_memmap_xm: [31]mm.Sbyte = [31]mm.Sbyte{
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    1,
    2,
    3,
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    4,
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    5,
    6,
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    7,
    8,
    9,
    10,
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    11,
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    12,
};

pub const mpp_effect_memmap_it: [27]mm.Sbyte = [27]mm.Sbyte{
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    1,
    2,
    2,
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    3,
    4,
    1,
    1,
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    12,
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
    13,
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 1))))),
};

pub const mpp_TABLE_FineSineData = [_]mm.Sbyte{
    0,
    2,
    3,
    5,
    6,
    8,
    9,
    11,
    12,
    14,
    16,
    17,
    19,
    20,
    22,
    23,
    24,
    26,
    27,
    29,
    30,
    32,
    33,
    34,
    36,
    37,
    38,
    39,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    56,
    57,
    58,
    59,
    59,
    60,
    60,
    61,
    61,
    62,
    62,
    62,
    63,
    63,
    63,
    64,
    64,
    64,
    64,
    64,
    64,
    64,
    64,
    64,
    64,
    64,
    63,
    63,
    63,
    62,
    62,
    62,
    61,
    61,
    60,
    60,
    59,
    59,
    58,
    57,
    56,
    56,
    55,
    54,
    53,
    52,
    51,
    50,
    49,
    48,
    47,
    46,
    45,
    44,
    43,
    42,
    41,
    39,
    38,
    37,
    36,
    34,
    33,
    32,
    30,
    29,
    27,
    26,
    24,
    23,
    22,
    20,
    19,
    17,
    16,
    14,
    12,
    11,
    9,
    8,
    6,
    5,
    3,
    2,
    0,
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 2))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 3))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 5))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 6))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 8))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 9))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 11))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 12))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 14))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 16))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 17))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 19))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 20))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 22))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 23))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 24))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 26))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 27))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 29))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 30))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 32))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 33))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 34))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 36))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 37))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 38))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 39))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 41))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 42))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 43))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 44))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 45))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 46))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 47))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 48))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 49))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 50))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 51))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 52))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 53))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 54))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 55))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 56))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 56))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 57))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 58))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 59))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 59))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 60))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 60))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 61))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 61))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 62))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 62))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 62))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 63))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 63))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 63))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 64))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 64))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 64))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 64))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 64))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 64))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 64))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 64))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 64))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 64))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 64))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 61))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 61))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 60))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 60))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 59))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 59))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 58))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 57))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 56))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 56))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 55))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 54))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 53))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 52))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 51))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 50))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 49))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 48))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 47))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 46))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 45))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 44))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 43))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 42))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 41))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 39))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 38))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 37))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 36))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 34))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 33))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 32))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 30))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 29))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 27))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 26))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 24))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 23))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 22))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 20))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 19))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 17))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 16))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 14))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 12))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 11))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 9))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 8))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 6))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 5))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 3))))),
    @as(mm.Sbyte, @bitCast(@as(i8, @truncate(-@as(c_int, 2))))),
};
